server:
  port: 8888
spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test_spring
    username: root
    password: 3141
